category = {
    'ANTISPAM': {'permanent': False, 'bounce_type': 'Hard'},
    'AUTOREPLY': {'permanent': False, 'bounce_type': 'AUTOREPLY'},
    'CONCURRENT': {'permanent': False, 'bounce_type': 'Soft'},
    'CONTENT_REJECT': {'permanent': False, 'bounce_type': 'Soft'},
    'COMMAND_REJECT': {'permanent': True, 'bounce_type': 'Hard'},
    'INTERNAL_ERROR': {'permanent': False, 'bounce_type': 'Temporary'},
    'DEFER': {'permanent': False, 'bounce_type': 'Soft'},
    'DELAYED': {'permanent': False, 'bounce_type': 'Temporary'},
    'DNS_LOOP': {'permanent': True, 'bounce_type': 'Hard'},
    'DNS_UNKNOWN': {'permanent': True, 'bounce_type': 'Hard'},
    'FULL': {'permanent': False, 'bounce_type': 'Soft'},
    'INACTIVE': {'permanent': True, 'bounce_type': 'Hard'},
    'LATIN_ONLY': {'permanent': False, 'bounce_type': 'Soft'},
    'OTHER': {'permanent': True, 'bounce_type': 'Generic'},
    'OVERSIZE': {'permanent': False, 'bounce_type': 'Soft'},
    'OUTOFOFFICE': {'permanent': False, 'bounce_type': 'Soft'},
    'UNKNOWN': {'permanent': True, 'bounce_type': 'Hard'},
    'UNRECOGNIZED': {'permanent': True, 'bounce_type': 'Hard'},
    'USER_REJECT': {'permanent': True, 'bounce_type': 'Hard'},
    'WARNING': {'permanent': False, 'bounce_type': 'Soft'},
}
